version: '3.4'

services:
  oneness_back:
    container_name: $projectName
    image: $registryName/$projectName:$workingEnv
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always