openapi: 3.0.0
info:
  version: 1.0.0
  title: ''
  description: ''

# Added by API Auto Mocking Plugin
servers:
  - description: The oneness movement API
    url: https://dev-oneness.andersenlab.dev/api/

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

schemas:
 $ref: "./schemas/_index.yaml"

paths:
  $ref: "./paths/_index.yaml"


