type: object
properties:
  id:
    type: integer
  title:
    type: string
    nullable: true
  description:
    type: string
    nullable: true
  type:
    type: string
    nullable: true
  locations:
    type: string
    nullable: true
  basic_location:
    type: string
    nullable: true
  deposit_instalment_payments:
    type: string
    nullable: true
  user_id:
    type: integer
  is_published:
    type: boolean
    nullable: true
  introduction:
    type: string
    nullable: true
  url:
    type: string
    nullable: true
  service_type_id:
    type: string
    nullable: true
  created_at:
    type: string
    nullable: true
    format: date-time
  updated_at:
    type: string
    nullable: true
    format: date-time
  deleted_at:
    type: string
    nullable: true
    format: date-time
