<?php

use Illuminate\Database\Migrations\Migration;
use App\Models\CustomEmail;


class AddClientPurchase extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        CustomEmail::upsert([
            ['id' => 124, 'text' => '<tr><td><p class="slate-p">Hi {{first_name}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details: </strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">From: {{schedule_start_date}} at {{schedule_start_time}} </p></td></tr><tr><td><p class="slate-p">To: {{schedule_end_date}} at {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_venue_name}} {{schedule_venue_address}} {{schedule_city}}, {{schedule_postcode}} {{schedule_country}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_purchase}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Deposit paid: {{deposit_paid}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">The client will pay the remaining over instalments as follows:</p></td></tr><tr><td><p class="slate-p">{{instalments}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">If the client does not keep up their payments, their booking may be cancelled.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 125, 'text' => '<tr><td><p class="slate-p">Hi {{first_name}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has purchased {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details: </strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Order Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}} </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_purchase}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Deposit paid: {{deposit_paid}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">The client will pay the remaining over instalments as follows:</p></td></tr><tr><td><p class="slate-p">{{instalments}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">If the client does not keep up their payments, their booking may be cancelled.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 127, 'text' => '<tr><td><p class="slate-p">Hi {{first_name}} </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details: </strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">From: {{schedule_start_date}}, {{schedule_start_time}} To: {{schedule_end_date}}, {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_purchase}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Deposit paid: {{deposit_paid}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">The client will pay the remaining over instalments as follows:</p></td></tr><tr><td><p class="slate-p">{{instalments}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">If the client does not keep up their payments, their booking may be cancelled.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
        ],
            ['id'],
            ['text']
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        CustomEmail::upsert([
            ['id' => 124, 'text' => '<tr><td><p class="slate-p">Hi {{first_name}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details: </strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">From: {{schedule_start_date}} at {{schedule_start_time}} </p></td></tr><tr><td><p class="slate-p">To: {{schedule_end_date}} at {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_venue_name}} {{schedule_venue_address}} {{schedule_city}}, {{schedule_postcode}} {{schedule_country}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_booking}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Deposit paid: {{deposit_paid}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">The client will pay the remaining over instalments as follows:</p></td></tr><tr><td><p class="slate-p">{{instalments}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">If the client does not keep up their payments, their booking may be cancelled.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 125, 'text' => '<tr><td><p class="slate-p">Hi {{first_name}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has purchased {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details: </strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Order Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}} </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_booking}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Deposit paid: {{deposit_paid}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">The client will pay the remaining over instalments as follows:</p></td></tr><tr><td><p class="slate-p">{{instalments}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">If the client does not keep up their payments, their booking may be cancelled.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 127, 'text' => '<tr><td><p class="slate-p">Hi {{first_name}} </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details: </strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">From: {{schedule_start_date}}, {{schedule_start_time}} To: {{schedule_end_date}}, {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_booking}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Deposit paid: {{deposit_paid}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">The client will pay the remaining over instalments as follows:</p></td></tr><tr><td><p class="slate-p">{{instalments}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">If the client does not keep up their payments, their booking may be cancelled.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
        ],
            ['id'],
            ['text']
        );
    }
}
