<?php

use Illuminate\Database\Migrations\Migration;
use App\Models\CustomEmail;

class AddPurchaseLinkInEmails extends Migration
{
    public function up()
    {
        CustomEmail::upsert([
            ['id' => 90, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi <span data-slate-template="true">{{first_name}}</span></p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Start date: {{schedule_start_date}} at {{schedule_start_time}}</p></td></tr><tr><td><p class="slate-p">End date: {{schedule_end_date}} at {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_purchase}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 92, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi <span data-slate-template="true">{{first_name}}</span></p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has purchased {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}  <span data-slate-template="true">{{schedule_city}}</span>  <span data-slate-template="true">{{schedule_country}}</span> </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_purchase}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">We recommend getting in touch with {{client_name}} directly via Holistify messaging to provide any further information they may need for {{service_name}}. </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 94, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi <span data-slate-template="true">{{first_name}}</span></p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Start date: {{schedule_start_date}} at {{schedule_start_time}}</p></td></tr><tr><td><p class="slate-p">End date: {{schedule_end_date}} at {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_venue_name}} {{schedule_venue_address}} {{schedule_city}} {{schedule_postcode}} {{schedule_country}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_purchase}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: {{price_name}}</p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 96, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi {{first_name}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has purchased {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Price option: {{price_name}}</p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}  {{schedule_city}} {{schedule_country}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_purchase}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">We recommend getting in touch with {{client_name}} directly via Holistify messaging to provide any further information they may need for {{service_name}}. </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
        ],
            ['id'],
            ['text']
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        CustomEmail::upsert([
            ['id' => 90, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi <span data-slate-template="true">{{first_name}}</span></p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Start date: {{schedule_start_date}} at {{schedule_start_time}}</p></td></tr><tr><td><p class="slate-p">End date: {{schedule_end_date}} at {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_booking}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 92, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi <span data-slate-template="true">{{first_name}}</span></p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has purchased {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Price option: <span data-slate-template="true">{{price_name}}</span> </p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}  <span data-slate-template="true">{{schedule_city}}</span>  <span data-slate-template="true">{{schedule_country}}</span> </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_booking}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">We recommend getting in touch with {{client_name}} directly via Holistify messaging to provide any further information they may need for {{service_name}}. </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 94, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi <span data-slate-template="true">{{first_name}}</span></p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has booked with you for {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Booking Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Booking reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Start date: {{schedule_start_date}} at {{schedule_start_time}}</p></td></tr><tr><td><p class="slate-p">End date: {{schedule_end_date}} at {{schedule_end_time}}</p></td></tr><tr><td><p class="slate-p">Location: {{schedule_venue_name}} {{schedule_venue_address}} {{schedule_city}} {{schedule_postcode}} {{schedule_country}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_booking}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">Price option: {{price_name}}</p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
            ['id' => 96, 'text' => '<tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Hi {{first_name}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Congratulations! {{client_name}} has purchased {{service_name}}.</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"><strong class="slate-bold">Purchase Details:</strong></p></td></tr><tr><td><p class="slate-p">{{service_name}} - {{schedule_name}}</p></td></tr><tr><td><p class="slate-p">Reference: {{booking_reference}}</p></td></tr><tr><td><p class="slate-p">Price option: {{price_name}}</p></td></tr><tr><td><p class="slate-p">Cost: {{total_paid}}</p></td></tr><tr><td><p class="slate-p">Quantity: <span data-slate-template="true">{{number_of_tickets_purchased}}</span> </p></td></tr><tr><td><p class="slate-p">Location: {{schedule_hosting_url}}  {{schedule_city}} {{schedule_country}}</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><a href="{{view_client_booking}}" target="_blank" rel="noreferrer" data-button-link="true" style="text-decoration:none"><span style="padding:10px 24px;margin-bottom:8px;color:#ffffff;text-align:center;background-color:#db7a6a;line-height:45px;border-radius:25px;cursor:pointer;user-select:none" contenteditable="false" >View Client Booking</span></a></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">We recommend getting in touch with {{client_name}} directly via Holistify messaging to provide any further information they may need for {{service_name}}. </p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p">Thank you</p></td></tr><tr><td><p class="slate-p">The Holistify Team</p></td></tr><tr><td><p class="slate-p"></p></td></tr><tr><td><p class="slate-p"></p></td></tr>'],
        ],
            ['id'],
            ['text']
        );
    }
}
